all:
	@echo "===================="
	@echo "| ADC_driver tests |"
	@echo "===================="
	@echo ""
	@$(MAKE) --no-print-directory -C tests_ADC_ADS1115_driver/
	@$(MAKE) --no-print-directory -C tests_ADC_MCP342x_driver/